### ISSUE TITLE
[Flow] __typename not marked a read-only

### ISSUE THREAD

**Issue by FezVrasta** [dotansimha/graphql-code-generator-community#117]
**Describe the bug**
 

**To Reproduce**

https://codesandbox.io/s/wizardly-moser-nsrl1?file=/types.js

1. My GraphQL schema:

Any schema

2. My GraphQL operations:

No operations.

3. My `codegen.yml` config file:

```
schema: schema.graphql
documents: document.graphql
generates:
  types.js:
    plugins:
      - flow
      - flow-operations
    config:
      useFlowReadOnlyTypes: true
```

**Expected behavior**
__typename should be read-only
