### ISSUE TITLE
[typescript-react-query] Does not use own types when combined with import-types and typescript-operations

### ISSUE THREAD

**Issue by IanVS** [dotansimha/graphql-code-generator-community#154]
**Describe the bug**
I would like to separate out my schema-types from operation-types+hooks, and I believe I've found the config which should accomplish it.  However, when using import-types-preset, _all_ of the types are referenced from the `Types` import, even if they're being exported from the same file.  

**To Reproduce**

https://codesandbox.io/s/graphql-code-generator-6909-lu5rm?file=/hooks.ts

Note typescript errors for `Types.UserQuery`, since `UserQuery` is defined in the same file, not `./types`.

1. My GraphQL schema:

See reproduction

2. My GraphQL operations:

See reproduction

3. My `codegen.yml` config file:

```yml
generates:
  ./types.ts:
    plugins:
      - typescript
  ./hooks.ts:
    preset: import-types
    presetConfig:
      typesPath: ./types
    plugins:
      - typescript-operations
      - typescript-react-query
```

**Expected behavior**
I expect that types being exported from `hooks.ts` are not attempted to be imported from `types.ts`.

**Environment:**

- OS: mac
- `@graphql-codegen/...`: latest, see reproduction
- NodeJS: 16

**Additional context**
A similar issue which was recently fixed: https://github.com/dotansimha/graphql-code-generator/issues/6520
