### ISSUE TITLE
@graphql-codegen/typescript-graphql-request uses wrong import for gql in ESM

### ISSUE THREAD

**Issue by ldrick** [dotansimha/graphql-code-generator-community#323]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-graphql-request

### Describe the bug

If you try to generate a ESM compatible sdk with `@graphql-codegen/typescript-graphql-request` it imports `gql` namespace, instead of `{gql}` function

### Your Example Website or App

https://the-guild.dev/graphql/codegen

### Steps to Reproduce the Bug or Issue

1. Go to https://the-guild.dev/graphql/codegen
2. Provide this codegen.yml:
```yml
generates:
  sdk.ts:
    plugins:
      - typescript
      - typescript-graphql-request
    config:
      emitLegacyCommonJSImports: false
```
3. See the
```typescript
import gql from 'graphql-tag';
```

### Expected behavior

should output
```typescript
import {gql} from 'graphql-tag';
```

### Platform

- OS: Linux
- NodeJS: 18.15.0
- `graphql` version: 16.6.0
- `@graphql-codegen/typescript-graphql-request` version: 4.5.9

### Additional context

Workaround:
```typescript
// gql-fix.ts
import { gql } from "graphql-tag";

export { gql };
```

and use it like:
```yml
generates:
  sdk.ts:
    plugins:
      - typescript
      - typescript-graphql-request
    config:
      emitLegacyCommonJSImports: false
      gqlImport: ./gql-fix.js#gql,
```

**Comment by simenandre** [comment]
Another workaround is:

```yaml
generates:
  sdk.ts:
    plugins:
      - typescript
      - typescript-graphql-request
    config:
      emitLegacyCommonJSImports: false
      gqlImport: graphql-tag#gql,
```
