### ISSUE TITLE
Type 'GraphCacheConfig' does not satisfy the constraint 'OfflineExchangeOpts'

### ISSUE THREAD

**Issue by nephix** [dotansimha/graphql-code-generator-community#337]
### Which packages are impacted by your issue?

```
@graphql-codegen/typescript-urql-graphcache
```

### Describe the bug

Generated type `GraphCacheConfig` does not satisfy urlq's `OfflineExchangeOpts` constraints:

```ts
Type 'GraphCacheConfig' does not satisfy the constraint 'OfflineExchangeOpts'.
  Types of property 'storage' are incompatible.
    Type 'StorageAdapter | undefined' is not assignable to type 'StorageAdapter'.
      Type 'undefined' is not assignable to type 'StorageAdapter'.ts(2344)
```

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

`codegen.yml`:

```yml
overwrite: true
schema: 'http://localhost:8080/graphql'
documents:
  - apps/**/*.graphql
  - packages/common/**/*.graphql
generates:
  packages/common/data/schema.introspection.ts:
    plugins:
      - 'urql-introspection'
    config:
      useTypeImports: true
      includeScalars: true
      includeEnums: true
      includeInputs: true
      includeDirectives: true
  packages/common/data/schema.ts:
    plugins:
      - typescript
      - typescript-urql-graphcache
    config:
      useTypeImports: true
  apps/:
    config:
      exportFragmentSpreadSubTypes: true
      withHooks: true
    plugins:
      - typescript-operations
      - typescript-urql
    preset: near-operation-file
    presetConfig:
      baseTypesPath: ~@common/data/schema
      extension: .generated.ts

```

Generate a `GraphCacheConfig` type and then:

```ts
import { createClient } from 'urql';
import { offlineExchange } from '@urql/exchange-graphcache';

return createClient({
  exchanges: [
    offlineExchange<GraphCacheConfig>({
      storage: makeAsyncStorage(),
    }),
  ],
});
```

### Expected behavior

No typescript errors

### Platform

- OS: macos
- NodeJS: `v16.18.0`
- `graphql` version: `^15.5.1`
- `@graphql-codegen/*` version(s): 
```
"@graphql-codegen/cli": "^3.3.0",
"@graphql-codegen/import-types-preset": "^2.2.4",
"@graphql-codegen/near-operation-file-preset": "^2.4.2",
"@graphql-codegen/typescript": "^3.0.3",
"@graphql-codegen/typescript-operations": "^3.0.3",
"@graphql-codegen/typescript-urql": "^3.7.0",
"@graphql-codegen/typescript-urql-graphcache": "^2.4.0",
"@graphql-codegen/urql-introspection": "2.2.1",
```
