### ISSUE TITLE
Allow arrays to be generated as const

### ISSUE THREAD

**Issue by omjadas** [dotansimha/graphql-code-generator-community#58]
**Is your feature request related to a problem? Please describe.**

I am interested in using the `enum-array` plugin, however I would prefer if the arrays were generated `as const`.

**Describe the solution you'd like**

Allow a config option that generates the arrays `as const`

**Describe alternatives you've considered**

Manually create const arrays

**Additional context**

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1674417409150

**Comment by hjoelh** [comment]
@omjadas or @saihaj would you mind sending me your usage of "typescript-enum-array" in codegen-config, I can't get it too work  🙏

```
  generates: {
    [`${generatedFileSystemLocation}/schema.gql`]: {
      // https://the-guild.dev/graphql/codegen/plugins/other/schema-ast#config-api-reference
      plugins: ["schema-ast"],
    },
    [`${generatedFileSystemLocation}/types.ts`]: {
      // https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-operations
      plugins: ["typescript", "typescript-operations", "typescript-enum-array"],
      config: {
        strictScalars: true,
        scalars,
      },
    },
    [`${generatedFileSystemLocation}/enums.ts`]: {
      plugins: ["typescript-enum-array"],
      config: {
        importFrom: `./types`,
        constArrays: true,
      },
    },

```

**Comment by omjadas** [comment]
This is our config

```yml
schema: ./schema.graphql
documents: ./lib/graphql/**/*.graphql
extensions:
  codegen:
    generates:
      ./lib/graphql/generated.ts:
        plugins:
          - typescript
          - typescript-apollo-client-helpers
          - typescript-enum-array
          - typescript-operations
          - typed-document-node
          - named-operations-object
          - fragment-matcher
        config:
          avoidOptionals:
            field: true
          constArrays: true
          defaultScalarType: unknown
          nonOptionalTypename: true
          useConsts: true
          useMembers: true

```
