### ISSUE TITLE
unexpected examples in `flow` and `flow-operations` documentation

### ISSUE THREAD

**Issue by Maxwell2022** [dotansimha/graphql-code-generator-community#850]
### Which packages are impacted by your issue?

@graphql-codegen/flow, @graphql-codegen/flow-operations

### Describe the bug

The documentation is incorrectly referencing typescript plugin and typescript file extensions in the flow-operation documentation

### Your Example Website or App

https://github.com/dotansimha/graphql-code-generator-community/blob/e0b563c5a1d0f8fa207c6bf1a7a7bb74d188f390/packages/plugins/flow/operations/src/config.ts#L41-L55

### Steps to Reproduce the Bug or Issue

1. go to https://the-guild.dev/graphql/codegen/plugins/flow/flow-operations
2. assert that examples are referencing `file.ts` and sometimes `typescript` plugins

### Expected behavior

Documentation should use a `.js` extension for the generated file
Plugins used should reference the plugin documented.

```yaml
generates:
  path/to/file.js:
    plugins:
      - flow
      - flow-operations
    config:
      useFlowExactObjects: false
```

### Screenshots or Videos

![Uploading image.png…]()

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.3.0]
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]
